blank_issues_enabled: false
contact_links:
  - name: ✋ Requesting a New Roadmap
    url: https://discord.gg/cJpEt5Qbwa
    about: Please do not open issues with roadmap requests, hop onto the discord server for that.
  - name: 💬 Chat
    url: https://discord.gg/cJpEt5Qbwa
    about: Join the community on our Discord server.
  - name: 🤝 Guidance
    url: https://discord.gg/cJpEt5Qbwa
    about: Join the community on our Discord server.
