name: Sends Daily AWS Costs to Slack
on:
  # Allow manual Run
  workflow_dispatch:
  # Run at 7:00 UTC every day
  schedule:
    - cron: "0 7 * * *"
jobs:
  aws_costs:
    runs-on: ubuntu-latest
    steps:
      - name: Get Costs
        env:
          AWS_KEY: ${{ secrets.COST_AWS_ACCESS_KEY }}
          AWS_SECRET: ${{ secrets.COST_AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.COST_AWS_REGION }}
        run: |
          npm install -g aws-cost-cli
          aws-cost -k $AWS_KEY -s $AWS_SECRET -r $AWS_REGION
