name: Clears Cloudfront Cache
on:
  # Allow manual Run
  workflow_dispatch:
  # Run at midnight utc
  schedule:
    - cron: '0 0 * * *'
jobs:
  aws_costs:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cloudfront Caching
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/roadmapsh/infra-ansible/actions/workflows/playbook.yml/dispatches \
            -d '{ "ref":"master", "inputs": { "playbook": "roadmap_web.yml", "tags": "cloudfront", "is_verbose": false } }'
