name: Update Sponsors

on:
  workflow_dispatch: # allow manual run
  schedule:
    - cron: '0 0 * * *' # run daily at 00:00 UTC

env:
  SPONSOR_SHEET_API_KEY: ${{ secrets.SPONSOR_SHEET_API_KEY }}
  SPONSOR_SHEET_ID: ${{ secrets.SPONSOR_SHEET_ID }}

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.13.4
      - name: Install dependencies
        run: |
          pnpm install
      - name: Update sponsors
        run: |
          node bin/update-sponsors.cjs
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: false
          branch: 'update-sponsors'
          base: 'master'
          labels: |
            sponsors
            automated pr
          reviewers: kamranahmedse
          commit-message: 'chore: update sponsors'
          title: 'Update Sponsor Banners'
          body: |
            Updates sponsor banners.
            Please review the changes and merge if everything looks good.
